describe('Cadastro', () => {
    it('Cadastro tipo Moto', () => {
        cy.visit('/deliver')
        cy.contains('h1', 'Cadastre-se para fazer entregas').should('be.visible')
        cy.get('input[placeholder*="Nome completo"]').type('Igor Gouveia')
        cy.get('input[placeholder*="CPF somente números"]').type('42736240014')
        cy.get('input[placeholder*="E-mail"]').type('igor.roichman@gmail.com')
        cy.get('input[placeholder*="Whatsapp"]').type('48996881234')
        cy.get('input[placeholder*="CEP"]').type('88317650')
        cy.get('input[value*="CEP"]').click()
        cy.get('input[placeholder*="Número"]').type('101')
        cy.get('input[placeholder*="Complemento"]').type('Casa')
        cy.get('img[alt*="Moto"]').click()
        cy.get('input[type=file]').invoke('show').selectFile('cypress/fixtures/cnh.jpg')
        cy.contains('button', 'Cadastre-se para fazer entregas').click()
        cy.contains('h2', 'Aí Sim...').should('be.visible')
    })

    it('Cadastro tipo Bicicleta', () => {
        cy.visit('/deliver')
        cy.contains('h1', 'Cadastre-se para fazer entregas').should('be.visible')
        cy.get('input[placeholder*="Nome completo"]').type('Igor Gouveia')
        cy.get('input[placeholder*="CPF somente números"]').type('42736240014')
        cy.get('input[placeholder*="E-mail"]').type('igor.roichman@gmail.com')
        cy.get('input[placeholder*="Whatsapp"]').type('48996881234')
        cy.get('input[placeholder*="CEP"]').type('88317650')
        cy.get('input[value*="CEP"]').click()
        cy.get('input[placeholder*="Número"]').type('101')
        cy.get('input[placeholder*="Complemento"]').type('Casa')
        cy.get('img[alt*="Bicicleta"]').click()
        cy.get('input[type=file]').invoke('show').selectFile('cypress/fixtures/cnh.jpg')
        cy.contains('button', 'Cadastre-se para fazer entregas').click()
        cy.contains('h2', 'Aí Sim...').should('be.visible')
    })

    it('Cadastro tipo Van/Carro', () => {
        cy.visit('/deliver')
        cy.contains('h1', 'Cadastre-se para fazer entregas').should('be.visible')
        cy.get('input[placeholder*="Nome completo"]').type('Igor Gouveia')
        cy.get('input[placeholder*="CPF somente números"]').type('42736240014')
        cy.get('input[placeholder*="E-mail"]').type('igor.roichman@gmail.com')
        cy.get('input[placeholder*="Whatsapp"]').type('48996881234')
        cy.get('input[placeholder*="CEP"]').type('88317650')
        cy.get('input[value*="CEP"]').click()
        cy.get('input[placeholder*="Número"]').type('101')
        cy.get('input[placeholder*="Complemento"]').type('Casa')
        cy.get('img[alt*="Van/Carro"]').click()
        cy.get('input[type=file]').invoke('show').selectFile('cypress/fixtures/cnh.jpg')
        cy.contains('button', 'Cadastre-se para fazer entregas').click()
        cy.contains('h2', 'Aí Sim...').should('be.visible')
    })

    it('Verificar CPF Inválido', () => {
        cy.visit('/deliver')
        cy.contains('h1', 'Cadastre-se para fazer entregas').should('be.visible')
        cy.get('input[placeholder*="Nome completo"]').type('Igor Gouveia')
        cy.get('input[placeholder*="CPF somente números"]').type('123456789')
        cy.get('input[placeholder*="E-mail"]').type('igor.roichman@gmail.com')
        cy.get('input[placeholder*="Whatsapp"]').type('48996881234')
        cy.get('input[placeholder*="CEP"]').type('88317650')
        cy.get('input[value*="CEP"]').click()
        cy.get('input[placeholder*="Número"]').type('101')
        cy.get('input[placeholder*="Complemento"]').type('Casa')
        cy.get('img[alt*="Van/Carro"]').click()
        cy.get('input[type=file]').invoke('show').selectFile('cypress/fixtures/cnh.jpg')
        cy.contains('button', 'Cadastre-se para fazer entregas').click()
        cy.contains('h2', 'Aí Sim...').should('not.exist')
        cy.contains('span', 'Oops! CPF inválido').should('be.visible')
    })

    it('Verificar E-mail Inválido', () => {
        cy.visit('/deliver')
        cy.contains('h1', 'Cadastre-se para fazer entregas').should('be.visible')
        cy.get('input[placeholder*="Nome completo"]').type('Igor Gouveia')
        cy.get('input[placeholder*="CPF somente números"]').type('42736240014')
        cy.get('input[placeholder*="E-mail"]').type('igor.roichmangmail.com')
        cy.get('input[placeholder*="Whatsapp"]').type('48996881234')
        cy.get('input[placeholder*="CEP"]').type('88317650')
        cy.get('input[value*="CEP"]').click()
        cy.get('input[placeholder*="Número"]').type('101')
        cy.get('input[placeholder*="Complemento"]').type('Casa')
        cy.get('img[alt*="Van/Carro"]').click()
        cy.get('input[type=file]').invoke('show').selectFile('cypress/fixtures/cnh.jpg')
        cy.contains('button', 'Cadastre-se para fazer entregas').click()
        cy.contains('h2', 'Aí Sim...').should('not.exist')
        
    })

    it('Verificar Campos obrigatórios', () => {
        cy.visit('/deliver')
        cy.contains('button', 'Cadastre-se para fazer entregas').click()
        cy.contains('h2', 'Aí Sim...').should('not.exist')
        cy.contains('É necessário informar o nome').should('be.visible') 
        cy.contains('É necessário informar o CPF').should('be.visible') 
        cy.contains('É necessário informar o email').should('be.visible') 
        cy.contains('É necessário informar o CEP').should('be.visible') 
        cy.contains('É necessário informar o número do endereço').should('be.visible') 
        cy.contains('Selecione o método de entrega').should('be.visible') 
        cy.contains('Adicione uma foto da sua CNH').should('be.visible') 
    })

    it('Verificar retorno Buscar CEP', () => {
        const cep = '88317-650'
        cy.visit('/deliver')
        cy.get('input[placeholder*="CEP"]').type(cep)
        cy.get('input[value*="CEP"]').click()
        cy.request('GET', `https://viacep.com.br/ws/${cep}/json/`).then((response) => {
            expect(response.status).to.eq(200)
            expect(response.body.cep).to.eq(cep)
        })
    })
})